# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hackbard/source/kalkulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hackbard/source/kalkulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hackbard/source/kalkulator/CMakeFiles /home/hackbard/source/kalkulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hackbard/source/kalkulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kalkulator

# Build rule for target.
kalkulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kalkulator
.PHONY : kalkulator

# fast build rule for target.
kalkulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/build
.PHONY : kalkulator/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/lisp/lisp_execution_context.o: src/model/lisp/lisp_execution_context.cpp.o
.PHONY : src/model/lisp/lisp_execution_context.o

# target to build an object file
src/model/lisp/lisp_execution_context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_execution_context.cpp.o
.PHONY : src/model/lisp/lisp_execution_context.cpp.o

src/model/lisp/lisp_execution_context.i: src/model/lisp/lisp_execution_context.cpp.i
.PHONY : src/model/lisp/lisp_execution_context.i

# target to preprocess a source file
src/model/lisp/lisp_execution_context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_execution_context.cpp.i
.PHONY : src/model/lisp/lisp_execution_context.cpp.i

src/model/lisp/lisp_execution_context.s: src/model/lisp/lisp_execution_context.cpp.s
.PHONY : src/model/lisp/lisp_execution_context.s

# target to generate assembly for a file
src/model/lisp/lisp_execution_context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_execution_context.cpp.s
.PHONY : src/model/lisp/lisp_execution_context.cpp.s

src/model/lisp/lisp_function_execution_context.o: src/model/lisp/lisp_function_execution_context.cpp.o
.PHONY : src/model/lisp/lisp_function_execution_context.o

# target to build an object file
src/model/lisp/lisp_function_execution_context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_function_execution_context.cpp.o
.PHONY : src/model/lisp/lisp_function_execution_context.cpp.o

src/model/lisp/lisp_function_execution_context.i: src/model/lisp/lisp_function_execution_context.cpp.i
.PHONY : src/model/lisp/lisp_function_execution_context.i

# target to preprocess a source file
src/model/lisp/lisp_function_execution_context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_function_execution_context.cpp.i
.PHONY : src/model/lisp/lisp_function_execution_context.cpp.i

src/model/lisp/lisp_function_execution_context.s: src/model/lisp/lisp_function_execution_context.cpp.s
.PHONY : src/model/lisp/lisp_function_execution_context.s

# target to generate assembly for a file
src/model/lisp/lisp_function_execution_context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_function_execution_context.cpp.s
.PHONY : src/model/lisp/lisp_function_execution_context.cpp.s

src/model/lisp/lisp_parser.o: src/model/lisp/lisp_parser.cpp.o
.PHONY : src/model/lisp/lisp_parser.o

# target to build an object file
src/model/lisp/lisp_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_parser.cpp.o
.PHONY : src/model/lisp/lisp_parser.cpp.o

src/model/lisp/lisp_parser.i: src/model/lisp/lisp_parser.cpp.i
.PHONY : src/model/lisp/lisp_parser.i

# target to preprocess a source file
src/model/lisp/lisp_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_parser.cpp.i
.PHONY : src/model/lisp/lisp_parser.cpp.i

src/model/lisp/lisp_parser.s: src/model/lisp/lisp_parser.cpp.s
.PHONY : src/model/lisp/lisp_parser.s

# target to generate assembly for a file
src/model/lisp/lisp_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_parser.cpp.s
.PHONY : src/model/lisp/lisp_parser.cpp.s

src/model/lisp/lisp_syntax_checker.o: src/model/lisp/lisp_syntax_checker.cpp.o
.PHONY : src/model/lisp/lisp_syntax_checker.o

# target to build an object file
src/model/lisp/lisp_syntax_checker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_syntax_checker.cpp.o
.PHONY : src/model/lisp/lisp_syntax_checker.cpp.o

src/model/lisp/lisp_syntax_checker.i: src/model/lisp/lisp_syntax_checker.cpp.i
.PHONY : src/model/lisp/lisp_syntax_checker.i

# target to preprocess a source file
src/model/lisp/lisp_syntax_checker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_syntax_checker.cpp.i
.PHONY : src/model/lisp/lisp_syntax_checker.cpp.i

src/model/lisp/lisp_syntax_checker.s: src/model/lisp/lisp_syntax_checker.cpp.s
.PHONY : src/model/lisp/lisp_syntax_checker.s

# target to generate assembly for a file
src/model/lisp/lisp_syntax_checker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_syntax_checker.cpp.s
.PHONY : src/model/lisp/lisp_syntax_checker.cpp.s

src/model/lisp/lisp_tokens.o: src/model/lisp/lisp_tokens.cpp.o
.PHONY : src/model/lisp/lisp_tokens.o

# target to build an object file
src/model/lisp/lisp_tokens.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_tokens.cpp.o
.PHONY : src/model/lisp/lisp_tokens.cpp.o

src/model/lisp/lisp_tokens.i: src/model/lisp/lisp_tokens.cpp.i
.PHONY : src/model/lisp/lisp_tokens.i

# target to preprocess a source file
src/model/lisp/lisp_tokens.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_tokens.cpp.i
.PHONY : src/model/lisp/lisp_tokens.cpp.i

src/model/lisp/lisp_tokens.s: src/model/lisp/lisp_tokens.cpp.s
.PHONY : src/model/lisp/lisp_tokens.s

# target to generate assembly for a file
src/model/lisp/lisp_tokens.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_tokens.cpp.s
.PHONY : src/model/lisp/lisp_tokens.cpp.s

src/model/lisp/lisp_value_parser.o: src/model/lisp/lisp_value_parser.cpp.o
.PHONY : src/model/lisp/lisp_value_parser.o

# target to build an object file
src/model/lisp/lisp_value_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_value_parser.cpp.o
.PHONY : src/model/lisp/lisp_value_parser.cpp.o

src/model/lisp/lisp_value_parser.i: src/model/lisp/lisp_value_parser.cpp.i
.PHONY : src/model/lisp/lisp_value_parser.i

# target to preprocess a source file
src/model/lisp/lisp_value_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_value_parser.cpp.i
.PHONY : src/model/lisp/lisp_value_parser.cpp.i

src/model/lisp/lisp_value_parser.s: src/model/lisp/lisp_value_parser.cpp.s
.PHONY : src/model/lisp/lisp_value_parser.s

# target to generate assembly for a file
src/model/lisp/lisp_value_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/lisp_value_parser.cpp.s
.PHONY : src/model/lisp/lisp_value_parser.cpp.s

src/model/lisp/value_converter.o: src/model/lisp/value_converter.cpp.o
.PHONY : src/model/lisp/value_converter.o

# target to build an object file
src/model/lisp/value_converter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/value_converter.cpp.o
.PHONY : src/model/lisp/value_converter.cpp.o

src/model/lisp/value_converter.i: src/model/lisp/value_converter.cpp.i
.PHONY : src/model/lisp/value_converter.i

# target to preprocess a source file
src/model/lisp/value_converter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/value_converter.cpp.i
.PHONY : src/model/lisp/value_converter.cpp.i

src/model/lisp/value_converter.s: src/model/lisp/value_converter.cpp.s
.PHONY : src/model/lisp/value_converter.s

# target to generate assembly for a file
src/model/lisp/value_converter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/lisp/value_converter.cpp.s
.PHONY : src/model/lisp/value_converter.cpp.s

src/model/table/table_cell.o: src/model/table/table_cell.cpp.o
.PHONY : src/model/table/table_cell.o

# target to build an object file
src/model/table/table_cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/table/table_cell.cpp.o
.PHONY : src/model/table/table_cell.cpp.o

src/model/table/table_cell.i: src/model/table/table_cell.cpp.i
.PHONY : src/model/table/table_cell.i

# target to preprocess a source file
src/model/table/table_cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/table/table_cell.cpp.i
.PHONY : src/model/table/table_cell.cpp.i

src/model/table/table_cell.s: src/model/table/table_cell.cpp.s
.PHONY : src/model/table/table_cell.s

# target to generate assembly for a file
src/model/table/table_cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/table/table_cell.cpp.s
.PHONY : src/model/table/table_cell.cpp.s

src/model/table/table_sheet.o: src/model/table/table_sheet.cpp.o
.PHONY : src/model/table/table_sheet.o

# target to build an object file
src/model/table/table_sheet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/table/table_sheet.cpp.o
.PHONY : src/model/table/table_sheet.cpp.o

src/model/table/table_sheet.i: src/model/table/table_sheet.cpp.i
.PHONY : src/model/table/table_sheet.i

# target to preprocess a source file
src/model/table/table_sheet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/table/table_sheet.cpp.i
.PHONY : src/model/table/table_sheet.cpp.i

src/model/table/table_sheet.s: src/model/table/table_sheet.cpp.s
.PHONY : src/model/table/table_sheet.s

# target to generate assembly for a file
src/model/table/table_sheet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/table/table_sheet.cpp.s
.PHONY : src/model/table/table_sheet.cpp.s

src/model/table/table_workbook_document.o: src/model/table/table_workbook_document.cpp.o
.PHONY : src/model/table/table_workbook_document.o

# target to build an object file
src/model/table/table_workbook_document.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/table/table_workbook_document.cpp.o
.PHONY : src/model/table/table_workbook_document.cpp.o

src/model/table/table_workbook_document.i: src/model/table/table_workbook_document.cpp.i
.PHONY : src/model/table/table_workbook_document.i

# target to preprocess a source file
src/model/table/table_workbook_document.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/table/table_workbook_document.cpp.i
.PHONY : src/model/table/table_workbook_document.cpp.i

src/model/table/table_workbook_document.s: src/model/table/table_workbook_document.cpp.s
.PHONY : src/model/table/table_workbook_document.s

# target to generate assembly for a file
src/model/table/table_workbook_document.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/table/table_workbook_document.cpp.s
.PHONY : src/model/table/table_workbook_document.cpp.s

src/model/table/table_workbook_file.o: src/model/table/table_workbook_file.cpp.o
.PHONY : src/model/table/table_workbook_file.o

# target to build an object file
src/model/table/table_workbook_file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/table/table_workbook_file.cpp.o
.PHONY : src/model/table/table_workbook_file.cpp.o

src/model/table/table_workbook_file.i: src/model/table/table_workbook_file.cpp.i
.PHONY : src/model/table/table_workbook_file.i

# target to preprocess a source file
src/model/table/table_workbook_file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/table/table_workbook_file.cpp.i
.PHONY : src/model/table/table_workbook_file.cpp.i

src/model/table/table_workbook_file.s: src/model/table/table_workbook_file.cpp.s
.PHONY : src/model/table/table_workbook_file.s

# target to generate assembly for a file
src/model/table/table_workbook_file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/model/table/table_workbook_file.cpp.s
.PHONY : src/model/table/table_workbook_file.cpp.s

src/tests/lisp/lisp_tests.o: src/tests/lisp/lisp_tests.cpp.o
.PHONY : src/tests/lisp/lisp_tests.o

# target to build an object file
src/tests/lisp/lisp_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tests/lisp/lisp_tests.cpp.o
.PHONY : src/tests/lisp/lisp_tests.cpp.o

src/tests/lisp/lisp_tests.i: src/tests/lisp/lisp_tests.cpp.i
.PHONY : src/tests/lisp/lisp_tests.i

# target to preprocess a source file
src/tests/lisp/lisp_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tests/lisp/lisp_tests.cpp.i
.PHONY : src/tests/lisp/lisp_tests.cpp.i

src/tests/lisp/lisp_tests.s: src/tests/lisp/lisp_tests.cpp.s
.PHONY : src/tests/lisp/lisp_tests.s

# target to generate assembly for a file
src/tests/lisp/lisp_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tests/lisp/lisp_tests.cpp.s
.PHONY : src/tests/lisp/lisp_tests.cpp.s

src/tests/lisp/lisp_value_tests.o: src/tests/lisp/lisp_value_tests.cpp.o
.PHONY : src/tests/lisp/lisp_value_tests.o

# target to build an object file
src/tests/lisp/lisp_value_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tests/lisp/lisp_value_tests.cpp.o
.PHONY : src/tests/lisp/lisp_value_tests.cpp.o

src/tests/lisp/lisp_value_tests.i: src/tests/lisp/lisp_value_tests.cpp.i
.PHONY : src/tests/lisp/lisp_value_tests.i

# target to preprocess a source file
src/tests/lisp/lisp_value_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tests/lisp/lisp_value_tests.cpp.i
.PHONY : src/tests/lisp/lisp_value_tests.cpp.i

src/tests/lisp/lisp_value_tests.s: src/tests/lisp/lisp_value_tests.cpp.s
.PHONY : src/tests/lisp/lisp_value_tests.s

# target to generate assembly for a file
src/tests/lisp/lisp_value_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tests/lisp/lisp_value_tests.cpp.s
.PHONY : src/tests/lisp/lisp_value_tests.cpp.s

src/tests/table/table_lisp_function_tests.o: src/tests/table/table_lisp_function_tests.cpp.o
.PHONY : src/tests/table/table_lisp_function_tests.o

# target to build an object file
src/tests/table/table_lisp_function_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tests/table/table_lisp_function_tests.cpp.o
.PHONY : src/tests/table/table_lisp_function_tests.cpp.o

src/tests/table/table_lisp_function_tests.i: src/tests/table/table_lisp_function_tests.cpp.i
.PHONY : src/tests/table/table_lisp_function_tests.i

# target to preprocess a source file
src/tests/table/table_lisp_function_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tests/table/table_lisp_function_tests.cpp.i
.PHONY : src/tests/table/table_lisp_function_tests.cpp.i

src/tests/table/table_lisp_function_tests.s: src/tests/table/table_lisp_function_tests.cpp.s
.PHONY : src/tests/table/table_lisp_function_tests.s

# target to generate assembly for a file
src/tests/table/table_lisp_function_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tests/table/table_lisp_function_tests.cpp.s
.PHONY : src/tests/table/table_lisp_function_tests.cpp.s

src/tests/tests.o: src/tests/tests.cpp.o
.PHONY : src/tests/tests.o

# target to build an object file
src/tests/tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tests/tests.cpp.o
.PHONY : src/tests/tests.cpp.o

src/tests/tests.i: src/tests/tests.cpp.i
.PHONY : src/tests/tests.i

# target to preprocess a source file
src/tests/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tests/tests.cpp.i
.PHONY : src/tests/tests.cpp.i

src/tests/tests.s: src/tests/tests.cpp.s
.PHONY : src/tests/tests.s

# target to generate assembly for a file
src/tests/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tests/tests.cpp.s
.PHONY : src/tests/tests.cpp.s

src/tools/tools.o: src/tools/tools.cpp.o
.PHONY : src/tools/tools.o

# target to build an object file
src/tools/tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tools/tools.cpp.o
.PHONY : src/tools/tools.cpp.o

src/tools/tools.i: src/tools/tools.cpp.i
.PHONY : src/tools/tools.i

# target to preprocess a source file
src/tools/tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tools/tools.cpp.i
.PHONY : src/tools/tools.cpp.i

src/tools/tools.s: src/tools/tools.cpp.s
.PHONY : src/tools/tools.s

# target to generate assembly for a file
src/tools/tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/tools/tools.cpp.s
.PHONY : src/tools/tools.cpp.s

src/view/cells_view_control.o: src/view/cells_view_control.cpp.o
.PHONY : src/view/cells_view_control.o

# target to build an object file
src/view/cells_view_control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/cells_view_control.cpp.o
.PHONY : src/view/cells_view_control.cpp.o

src/view/cells_view_control.i: src/view/cells_view_control.cpp.i
.PHONY : src/view/cells_view_control.i

# target to preprocess a source file
src/view/cells_view_control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/cells_view_control.cpp.i
.PHONY : src/view/cells_view_control.cpp.i

src/view/cells_view_control.s: src/view/cells_view_control.cpp.s
.PHONY : src/view/cells_view_control.s

# target to generate assembly for a file
src/view/cells_view_control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/cells_view_control.cpp.s
.PHONY : src/view/cells_view_control.cpp.s

src/view/table_cell_format_dlg.o: src/view/table_cell_format_dlg.cpp.o
.PHONY : src/view/table_cell_format_dlg.o

# target to build an object file
src/view/table_cell_format_dlg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_cell_format_dlg.cpp.o
.PHONY : src/view/table_cell_format_dlg.cpp.o

src/view/table_cell_format_dlg.i: src/view/table_cell_format_dlg.cpp.i
.PHONY : src/view/table_cell_format_dlg.i

# target to preprocess a source file
src/view/table_cell_format_dlg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_cell_format_dlg.cpp.i
.PHONY : src/view/table_cell_format_dlg.cpp.i

src/view/table_cell_format_dlg.s: src/view/table_cell_format_dlg.cpp.s
.PHONY : src/view/table_cell_format_dlg.s

# target to generate assembly for a file
src/view/table_cell_format_dlg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_cell_format_dlg.cpp.s
.PHONY : src/view/table_cell_format_dlg.cpp.s

src/view/table_column_headers_control.o: src/view/table_column_headers_control.cpp.o
.PHONY : src/view/table_column_headers_control.o

# target to build an object file
src/view/table_column_headers_control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_column_headers_control.cpp.o
.PHONY : src/view/table_column_headers_control.cpp.o

src/view/table_column_headers_control.i: src/view/table_column_headers_control.cpp.i
.PHONY : src/view/table_column_headers_control.i

# target to preprocess a source file
src/view/table_column_headers_control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_column_headers_control.cpp.i
.PHONY : src/view/table_column_headers_control.cpp.i

src/view/table_column_headers_control.s: src/view/table_column_headers_control.cpp.s
.PHONY : src/view/table_column_headers_control.s

# target to generate assembly for a file
src/view/table_column_headers_control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_column_headers_control.cpp.s
.PHONY : src/view/table_column_headers_control.cpp.s

src/view/table_control.o: src/view/table_control.cpp.o
.PHONY : src/view/table_control.o

# target to build an object file
src/view/table_control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_control.cpp.o
.PHONY : src/view/table_control.cpp.o

src/view/table_control.i: src/view/table_control.cpp.i
.PHONY : src/view/table_control.i

# target to preprocess a source file
src/view/table_control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_control.cpp.i
.PHONY : src/view/table_control.cpp.i

src/view/table_control.s: src/view/table_control.cpp.s
.PHONY : src/view/table_control.s

# target to generate assembly for a file
src/view/table_control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_control.cpp.s
.PHONY : src/view/table_control.cpp.s

src/view/table_formula_text_control.o: src/view/table_formula_text_control.cpp.o
.PHONY : src/view/table_formula_text_control.o

# target to build an object file
src/view/table_formula_text_control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_formula_text_control.cpp.o
.PHONY : src/view/table_formula_text_control.cpp.o

src/view/table_formula_text_control.i: src/view/table_formula_text_control.cpp.i
.PHONY : src/view/table_formula_text_control.i

# target to preprocess a source file
src/view/table_formula_text_control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_formula_text_control.cpp.i
.PHONY : src/view/table_formula_text_control.cpp.i

src/view/table_formula_text_control.s: src/view/table_formula_text_control.cpp.s
.PHONY : src/view/table_formula_text_control.s

# target to generate assembly for a file
src/view/table_formula_text_control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_formula_text_control.cpp.s
.PHONY : src/view/table_formula_text_control.cpp.s

src/view/table_row_headers_control.o: src/view/table_row_headers_control.cpp.o
.PHONY : src/view/table_row_headers_control.o

# target to build an object file
src/view/table_row_headers_control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_row_headers_control.cpp.o
.PHONY : src/view/table_row_headers_control.cpp.o

src/view/table_row_headers_control.i: src/view/table_row_headers_control.cpp.i
.PHONY : src/view/table_row_headers_control.i

# target to preprocess a source file
src/view/table_row_headers_control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_row_headers_control.cpp.i
.PHONY : src/view/table_row_headers_control.cpp.i

src/view/table_row_headers_control.s: src/view/table_row_headers_control.cpp.s
.PHONY : src/view/table_row_headers_control.s

# target to generate assembly for a file
src/view/table_row_headers_control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_row_headers_control.cpp.s
.PHONY : src/view/table_row_headers_control.cpp.s

src/view/table_sheet_view.o: src/view/table_sheet_view.cpp.o
.PHONY : src/view/table_sheet_view.o

# target to build an object file
src/view/table_sheet_view.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_sheet_view.cpp.o
.PHONY : src/view/table_sheet_view.cpp.o

src/view/table_sheet_view.i: src/view/table_sheet_view.cpp.i
.PHONY : src/view/table_sheet_view.i

# target to preprocess a source file
src/view/table_sheet_view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_sheet_view.cpp.i
.PHONY : src/view/table_sheet_view.cpp.i

src/view/table_sheet_view.s: src/view/table_sheet_view.cpp.s
.PHONY : src/view/table_sheet_view.s

# target to generate assembly for a file
src/view/table_sheet_view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kalkulator.dir/build.make CMakeFiles/kalkulator.dir/src/view/table_sheet_view.cpp.s
.PHONY : src/view/table_sheet_view.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kalkulator"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model/lisp/lisp_execution_context.o"
	@echo "... src/model/lisp/lisp_execution_context.i"
	@echo "... src/model/lisp/lisp_execution_context.s"
	@echo "... src/model/lisp/lisp_function_execution_context.o"
	@echo "... src/model/lisp/lisp_function_execution_context.i"
	@echo "... src/model/lisp/lisp_function_execution_context.s"
	@echo "... src/model/lisp/lisp_parser.o"
	@echo "... src/model/lisp/lisp_parser.i"
	@echo "... src/model/lisp/lisp_parser.s"
	@echo "... src/model/lisp/lisp_syntax_checker.o"
	@echo "... src/model/lisp/lisp_syntax_checker.i"
	@echo "... src/model/lisp/lisp_syntax_checker.s"
	@echo "... src/model/lisp/lisp_tokens.o"
	@echo "... src/model/lisp/lisp_tokens.i"
	@echo "... src/model/lisp/lisp_tokens.s"
	@echo "... src/model/lisp/lisp_value_parser.o"
	@echo "... src/model/lisp/lisp_value_parser.i"
	@echo "... src/model/lisp/lisp_value_parser.s"
	@echo "... src/model/lisp/value_converter.o"
	@echo "... src/model/lisp/value_converter.i"
	@echo "... src/model/lisp/value_converter.s"
	@echo "... src/model/table/table_cell.o"
	@echo "... src/model/table/table_cell.i"
	@echo "... src/model/table/table_cell.s"
	@echo "... src/model/table/table_sheet.o"
	@echo "... src/model/table/table_sheet.i"
	@echo "... src/model/table/table_sheet.s"
	@echo "... src/model/table/table_workbook_document.o"
	@echo "... src/model/table/table_workbook_document.i"
	@echo "... src/model/table/table_workbook_document.s"
	@echo "... src/model/table/table_workbook_file.o"
	@echo "... src/model/table/table_workbook_file.i"
	@echo "... src/model/table/table_workbook_file.s"
	@echo "... src/tests/lisp/lisp_tests.o"
	@echo "... src/tests/lisp/lisp_tests.i"
	@echo "... src/tests/lisp/lisp_tests.s"
	@echo "... src/tests/lisp/lisp_value_tests.o"
	@echo "... src/tests/lisp/lisp_value_tests.i"
	@echo "... src/tests/lisp/lisp_value_tests.s"
	@echo "... src/tests/table/table_lisp_function_tests.o"
	@echo "... src/tests/table/table_lisp_function_tests.i"
	@echo "... src/tests/table/table_lisp_function_tests.s"
	@echo "... src/tests/tests.o"
	@echo "... src/tests/tests.i"
	@echo "... src/tests/tests.s"
	@echo "... src/tools/tools.o"
	@echo "... src/tools/tools.i"
	@echo "... src/tools/tools.s"
	@echo "... src/view/cells_view_control.o"
	@echo "... src/view/cells_view_control.i"
	@echo "... src/view/cells_view_control.s"
	@echo "... src/view/table_cell_format_dlg.o"
	@echo "... src/view/table_cell_format_dlg.i"
	@echo "... src/view/table_cell_format_dlg.s"
	@echo "... src/view/table_column_headers_control.o"
	@echo "... src/view/table_column_headers_control.i"
	@echo "... src/view/table_column_headers_control.s"
	@echo "... src/view/table_control.o"
	@echo "... src/view/table_control.i"
	@echo "... src/view/table_control.s"
	@echo "... src/view/table_formula_text_control.o"
	@echo "... src/view/table_formula_text_control.i"
	@echo "... src/view/table_formula_text_control.s"
	@echo "... src/view/table_row_headers_control.o"
	@echo "... src/view/table_row_headers_control.i"
	@echo "... src/view/table_row_headers_control.s"
	@echo "... src/view/table_sheet_view.o"
	@echo "... src/view/table_sheet_view.i"
	@echo "... src/view/table_sheet_view.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

